# Generated by Django 5.1.3 on 2024-12-25 08:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='delivery_status',
            field=models.ForeignKey(default='Collecting', null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.deliverystatus'),
        ),
    ]
