# Generated by Django 5.1.3 on 2024-12-25 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_delivery_delivery_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.ForeignKey(default='Not paid', null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.orderstatus'),
        ),
    ]
